server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SpringVueMSDB?serverTimezone=GMT%2d4
    username: root
    password: 12345678
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
