server:
  port: 9191

spring:
  datasource:
    url: jdbc:mysql://34.69.254.236/SpringVueMSDB?cloudSqlInstance=logistic-inventory-351314:us-central1:myron
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  setting for implementing feature 1
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
